push-docker-image:
  extends:
    file: ../.common/docker-compose.yml
    service: src
  image: docker:1.9.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  entrypoint: docker push chrisdostert/short-url-svc
  environment:
      - DOCKER_EMAIL
      - DOCKER_PASSWORD
      - DOCKER_USERNAME