integration-test:
  extends:
    file: ../.common/docker-compose.yml
    service: sbt
  entrypoint: sbt coverage it:test
  env_file:
    - ../.common/local-db.env
  links:
    - mysql
mysql:
  extends:
    file: ../.common/docker-compose.yml
    service: mysql