build-docker-image:
  extends:
    file: ../.common/docker-compose.yml
    service: src
  image: docker:1.9.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  entrypoint: docker build -t chrisdostert/short-url-svc target/docker/stage